name: Deploy to Staging
on:
  push:
    branches:
      - chore/v2

jobs:
  # tag-new-version:
  #   uses: seamuslowry/workflows/.github/workflows/tag.yml@main
  #   secrets:
  #     gh_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    # needs: tag-new-version # does not currently use output, but should run after tagging
    uses: seamuslowry/workflows/.github/workflows/deploy_python_functions.yml@main
    with:
      name: hundredandten
    secrets:
      azure_publish_profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
